<?
$qs[]="El CEII fue creado originalmente con la denominación de Centro de Estudios sobre innovación Institucional para la Gobernabilidad democrática en octubre de 2002, por resolución n° 205/02 del Consejo Directivo de la Facultad de Ciencias políticas y Sociales de la UNCuyo (Mendoza, Argentina). Desde entonces funciona en dicho ámbito institucional y está integrado como unidad de investigación al Conicet -N° 20.658-. En su primera etapa fue dirigido por el Lic. Walter José Cueto y un Consejo Asesor constituido por los doctores Isidoro Cheresky (Instituto Gino Germani-Universidad de Buenos Aires) Dardo Pérez Guilhou (Instituto Argentino de Estudios Constitucionales y Políticos y Universidad Nacional de Cuyo) y Manuel Alcántara Sáenz (Universidad de Salamanca). Con los años dicha conformación fue variando incorporándose nuevos investigadores. En el 2016, estas modificaciones se plasman, mediante resolución n° 214/16 CD, en una nueva estructura, dirigida por la Dra. María Melina Guardamagna, Co-dirigida por la Dra. Alicia Marcela Ballabio, junto a un Consejo Asesor integrado por el Lic. Walter José Cueto (CEII & UNCuyo); la Especialista Cristina Díaz (UNR & UNL) y el Dr. Arturo Fernández (Centro de Estudios e Investigaciones Laborales. CONICET).";
$qs[]="Desde su origen, la preocupación por la idea de Democracia, su fortalecimiento en Argentina y sus provincias y el convencimiento que era necesario aportar innovación a las viejas instituciones, crear y recrear derechos y democratizar las prácticas sociopolíticas configuraron el impulso central del sentido y alcance del nuevo Centro de Estudios. Para ello fue necesario impulsar este espacio profesional y académico que integrara especialmente el ímpetu, la fuerza, la iniciativa y la capacidad de estudiantes avanzados y jóvenes graduados, que buscaban un lugar de desarrollo personal y de vinculación con las prácticas laborales. Lo cierto es que el CEII siempre ha priorizado entre sus objetivos la formación de posgrado y de nuevos investigadores, la realización de actividades de consultoría profesional y el desarrollo de proyectos de investigación.";

$qs[]="El Centro ha sido y es el lugar de trabajo de becarios e investigadores de la Secretaría de Ciencia, técnica y Postgrado de la Universidad Nacional de Cuyo y del Consejo Nacional de Investigaciones Científicas y técnicas (CONICET) y de algunos miembros que realizan carreras de postgrado y especialmente doctorados en la propia UNCuyo como en otras universidades nacionales. también respalda e impulsa tesistas de grado y graduados que realizan tareas docentes.";
$qs[]="A partir de octubre de 2001 se inician las primeras observaciones electorales sistemáticas dentro de Mendoza y en otras provincias, con autofinanciamiento y en convenio con fundaciones y gobiernos provinciales. también, por convenio con la Secretaría Administrativa, Legal y técnica del Gobierno de Mendoza, se realizaron observaciones electorales entre 2004/05 durante las experiencias de implementación de voto electrónico. Simultáneamente, con la aplicación de la observación directa como técnica cualitativa, se han realizado otras actividades de consultoría utilizando entrevistas en profundidad, grupos focales y encuestas, en particular para el Programa Jefes/Jefas de Hogar en departamentos de Mendoza y en convenio con la Universidad de Tres de Febrero y el Banco Mundial.";

$qs[]="El CEII también ha realizado auditorías ciudadanas en municipios de las provincias de San Luis y Mendoza en contratos con el PNUD y la Subsecretaria para la Reforma Institucional y Fortalecimiento de la Democracia de la Jefatura de Gabinete de Ministros de la Presidencia de la Nación. La información de campo se obtenía en base a grupos focales y  encuestas. Además se aplicó una auditoría ciudadana a la Legislatura de Mendoza en acuerdo con el H. Senado de la Provincia.";
$qs[]="En el marco de los objetivos del Centro de Estudios y desde su creación se han concluido los proyectos bianuales: 'Elecciones, ciudadanía e instituciones políticas en Mendoza: un estudio a partir de la observación como método' (06/F134-2002/04); 'Legislatura y calidad democrática en Mendoza: un enfoque de auditoría ciudadana' (06/F169-2005/07); 'Legislatura y calidad democrática en Mendoza (Segunda Parte) 'en la perspectiva de los actores legislativos-' (06/F205-2007/09); 'Legislatura y Calidad democrática en Mendoza (Tercera parte) & Una revisión crítica del enfoque teórico, la metodología y los resultados' & (06/F246- 2009/2011); 'Políticas Públicas y Calidad de la Democracia El caso de la Política Presupuestaria en Mendoza' (06/F294- 2011/2013); 'La implementación de una política pública en contexto de complejidad normativa: el caso del ordenamiento territorial en Mendoza a partir de 2009' (06/F334- 2013/2015). Actualmente y en forma conjunta con el Departamento de Economía Política y Administración Rural (DEPAR) de la Facultad de Ciencias Agrarias estamos trabajando en los siguientes proyectos: 'La implementación de las políticas de Ordenamiento Territorial en Mendoza: heterogeneidades y (des)articulaciones en el nivel municipal' (F025 & 2016/2018) y 'Desarrollo rural con enfoque territorial: la implementación de las políticas vinculadas al desarrollo territorial en Mendoza' (A068 & 2016/2018), todos con el respaldo de la Secretaría de Ciencia y técnica de la UNCuyo.";

$qs[]="El Centro de Estudios ha editado y difundido su producción en jornadas, seminarios y congresos nacionales e internacionales de investigación 'especialmente en los de la Sociedad Argentina de Análisis Político (SAAP) y en los nacionales sobre Democracia (Rosario). Así como tambiém en capítulos de libros y numerosas publicaciones indexadas y reconocidas internacionalmente.";
$qs[]="Como parte de la transferencia de los conocimientos generados, el CEII ha organizado y dictado materias electivas, principalmente en la Facultad de Ciencias políticas y Sociales de la UNCuyo, seminarios, jornadas y congresos. Sus miembros, además dictan cursos en el nivel de grado y posgrado de diversas unidades acadámicas de la UNCuyo y en otras universidades.";

$qs[]="En el amplio espacio de la innovación institucional se ha trabajado también con técnicas de presupuesto participativo y planificación estratágica y en el equipo hay profesionales especializados en el manejo de metodologías cuanti/cuali y en análisis, diseño y evaluación de políticas públicas, temáticas sobre las cuales los miembros suelen ser convocados por medios de comunicación.";
$qs[]="El Centro mantiene relaciones permanentes de cooperación con organismos locales, nacionales e internacionales y con instituciones, organizaciones de la sociedad civil y empresarias preocupadas por las reformas políticas e institucionales provinciales y nacionales, por la calidad de las prácticas democráticas y por la formulación e implementación de políticas públicas en los diversos ámbitos de gobierno, local, provincial y nacional.";